name: config
version: 0.8.4
description: A package for parsing command-line arguments and configuration files.
repository: https://github.com/serverpod/cli_tools
issue_tracker: https://github.com/serverpod/cli_tools/issues
documentation: https://github.com/serverpod/cli_tools/blob/main/packages/config/README.md

topics:
  - cli
  - args
  - command
  - configuration
  - yaml

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.7.0
  collection: ^1.18.0
  meta: ^1.11.0
  path: ^1.8.2
  rfc_6901: ^0.2.0
  yaml: ^3.1.2

dev_dependencies:
  serverpod_lints: '>=2.7.0'
  test: ^1.25.0
  test_descriptor: ^2.0.0
